topic_camera: "/dope/webcam_rgb_raw"
topic_publishing: "dope"
frame_id: "/dope"

# Comment any of these lines to prevent detection / pose estimation of that object
weights: {
    #  "1_A":"train_1_HUGE_vgg-_stage3/net_epoch_5.pth", 
    #  "1_B":"train_1_HUGE_vgg-_stage3/net_epoch_10.pth", 
    #  "1_C":"train_1_HUGE_vgg-_stage3/net_epoch_15.pth", 
    #  "1_D":"train_1_HUGE_vgg-_stage3/net_epoch_20.pth", 

    #  "2_A":"train_2_HUGE_vgg-_stage3/net_epoch_5.pth", 
    #  "2_B":"train_2_HUGE_vgg-_stage3/net_epoch_10.pth", 
    #  "2_C":"train_2_HUGE_vgg-_stage3/net_epoch_15.pth", 
    #  "2_D":"train_2_HUGE_vgg-_stage3/net_epoch_20.pth", 

     "3_A":"train_3_HUGE_vgg-_stage3/net_epoch_5.pth", 
     "3_B":"train_3_HUGE_vgg-_stage3/net_epoch_10.pth", 
     "3_C":"train_3_HUGE_vgg-_stage3/net_epoch_15.pth", 
     "3_D":"train_3_HUGE_vgg-_stage3/net_epoch_20.pth", 
}

# Cuboid dimension in cm x,y,z
dimensions: {
    "1_A" : [4.4,4.3,4.2], #1
    "1_B" : [4.4,4.3,4.2], #1
    "1_C" : [4.4,4.3,4.2], #1
    "1_D" : [4.4,4.3,4.2], #1

    "2_A" : [5.68,3.9,4.6], #2
    "2_B" : [3.9,5.68,4.6], #2
    "2_C" : [5.68,3.9,4.6], #2
    "2_D" : [3.9,5.68,4.6], #2



    "3_A" : [6.2,7,4.59],  #3
    "3_B" : [6.2,7,4.59],  #3
    "3_C" : [6.2,7,4.59],  #3
    "3_D" : [6.2,7,4.59],  #3

}

draw_colors: {
    "1_A" : [13, 255, 128],  # green
    "1_B" : [255, 255, 255],  # while
    "1_C" : [0, 104, 255],  # blue
    "1_D" : [217,12, 232],  # magenta

    "2_A" : [13, 255, 128],  # green
    "2_B" : [255, 255, 255],  # while
    "2_C" : [0, 104, 255],  # blue
    "2_D" : [217,12, 232],  # magenta

    "3_A" : [13, 255, 128],  # green
    "3_B" : [255, 255, 255],  # while
    "3_C" : [0, 104, 255],  # blue
    "3_D" : [217,12, 232],  # magenta
}

# Camera intrinsics (Logitech C920)
camera_settings: {
    "name": "Viewpoint",
    "width": 512,
    "height": 512,
    "fx": 256,
    "fy": 256,
    "cx": 256,
    "cy": 256
}

# Config params for DOPE
thresh_angle: 0.5
thresh_map: 0.01
sigma: 3
thresh_points: 0.1
