topic_camera: "/dope/webcam_rgb_raw"
topic_publishing: "dope"
frame_id: "/dope"

# Comment any of these lines to prevent detection / pose estimation of that object
weights: {
    #  "1_e1":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_1.pth", 
    #  "1_e2":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_2.pth", 
    #  "1_e3":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_3.pth", 
    #  "1_e4":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_4.pth", 
    #  "1_e5":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_5.pth", 
    #  "1_e6":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_6.pth", 
    #  "1_e7":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_7.pth", 
    #  "1_e8":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_8.pth", 
    #  "1_e9":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_9.pth", 
    #  "1_e10":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_10.pth", 
    #  "1_e11":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_11.pth", 
    #  "1_e12":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_12.pth", 
     "1_e13":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_13.pth", 
     "1_e14":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_14.pth", 
    #  "1_e15":"exp2/train_1_HUGE_vgg-_stage3/net_epoch_15.pth", 
     
    #  "2_e1":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_1.pth", 
    #  "2_e2":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_2.pth", 
    #  "2_e3":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_3.pth", 
    #  "2_e4":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_4.pth", 
    #  "2_e5":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_5.pth", 
    #  "2_e6":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_6.pth", 
    #  "2_e7":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_7.pth", 
    #  "2_e8":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_8.pth", 
    #  "2_e9":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_9.pth", 
    #  "2_e10":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_10.pth", 
    #  "2_e11":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_11.pth", 
    #  "2_e12":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_12.pth", 
    #  "2_e13":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_13.pth", 
    #  "2_e14":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_14.pth", 
    #  "2_e15":"exp2/train_2_HUGE_vgg-_stage3/net_epoch_15.pth", 
    
    #  "3_e1":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_1.pth", 
    #  "3_e2":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_2.pth", 
    #  "3_e3":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_3.pth", 
    #  "3_e4":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_4.pth", 
    #  "3_e5":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_5.pth", 
    #  "3_e6":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_6.pth", 
    #  "3_e7":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_7.pth", 
    #  "3_e8":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_8.pth", 
    #  "3_e9":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_9.pth", 
    #  "3_e10":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_10.pth", 
    #  "3_e11":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_11.pth", 
    #  "3_e12":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_12.pth", 
    #  "3_e13":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_13.pth", 
    #  "3_e14":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_14.pth", 
    #  "3_e15":"exp2/train_3_HUGE_vgg-_stage3/net_epoch_15.pth", 

    #  "V2_e1":"exp1/train_1_v2_vgg-_stage3/net_epoch_1.pth", 
    #  "V2_e2":"exp1/train_1_v2_vgg-_stage3/net_epoch_2.pth", 
    #  "V2_e3":"exp1/train_1_v2_vgg-_stage3/net_epoch_3.pth", 
    #  "V2_e4":"exp1/train_1_v2_vgg-_stage3/net_epoch_4.pth", 
    #  "V2_e5":"exp1/train_1_v2_vgg-_stage3/net_epoch_5.pth", 
    #  "V2_e6":"exp1/train_1_v2_vgg-_stage3/net_epoch_6.pth", 
    #  "V2_e7":"exp1/train_1_v2_vgg-_stage3/net_epoch_7.pth", 
    #  "V2_e8":"exp1/train_1_v2_vgg-_stage3/net_epoch_8.pth", 
    #  "V2_e9":"exp1/train_1_v2_vgg-_stage3/net_epoch_9.pth", 
    #  "V2_e10":"exp1/train_1_v2_vgg-_stage3/net_epoch_10.pth", 
    #  "V2_e11":"exp1/train_1_v2_vgg-_stage3/net_epoch_11.pth", 
    #  "V2_e12":"exp1/train_1_v2_vgg-_stage3/net_epoch_12.pth", 
    #  "V2_e13":"exp1/train_1_v2_vgg-_stage3/net_epoch_13.pth", 
    #  "V2_e14":"exp1/train_1_v2_vgg-_stage3/net_epoch_14.pth", 
    #  "V2_e15":"exp1/train_1_v2_vgg-_stage3/net_epoch_15.pth",
    #  "V3_e1":"exp1/train_1_v3_vgg-_stage3/net_epoch_1.pth", 
    #  "V3_e2":"exp1/train_1_v3_vgg-_stage3/net_epoch_2.pth", 
    #  "V3_e3":"exp1/train_1_v3_vgg-_stage3/net_epoch_3.pth", 
    #  "V3_e4":"exp1/train_1_v3_vgg-_stage3/net_epoch_4.pth", 
    #  "V3_e5":"exp1/train_1_v3_vgg-_stage3/net_epoch_5.pth", 
    #  "V3_e6":"exp1/train_1_v3_vgg-_stage3/net_epoch_6.pth", 
    #  "V3_e7":"exp1/train_1_v3_vgg-_stage3/net_epoch_7.pth", 
    #  "V3_e8":"exp1/train_1_v3_vgg-_stage3/net_epoch_8.pth", 
    #  "V3_e9":"exp1/train_1_v3_vgg-_stage3/net_epoch_9.pth", 
    #  "V3_e10":"exp1/train_1_v3_vgg-_stage3/net_epoch_10.pth", 
    #  "V3_e11":"exp1/train_1_v3_vgg-_stage3/net_epoch_11.pth", 
    #  "V3_e12":"exp1/train_1_v3_vgg-_stage3/net_epoch_12.pth", 
    #  "V3_e13":"exp1/train_1_v3_vgg-_stage3/net_epoch_13.pth", 
    #  "V3_e14":"exp1/train_1_v3_vgg-_stage3/net_epoch_14.pth", 
    #  "V3_e15":"exp1/train_1_v3_vgg-_stage3/net_epoch_15.pth",
    #  "V2V3_e1":"exp1/train_1_v2+v3_vgg-_stage3/net_epoch_1.pth", 
    #  "V2V3_e2":"exp1/train_1_v2+v3_vgg-_stage3/net_epoch_2.pth", 
    #  "V2V3_e3":"exp1/train_1_v2+v3_vgg-_stage3/net_epoch_3.pth", 
    #  "V2V3_e4":"exp1/train_1_v2+v3_vgg-_stage3/net_epoch_4.pth", 
    #  "V2V3_e5":"exp1/train_1_v2+v3_vgg-_stage3/net_epoch_5.pth", 

    #  "V2_e11":"exp1/train_1_v2_vgg_stage3/net_epoch_11.pth", 
    #  "V2_e12":"exp1/train_1_v2_vgg_stage3/net_epoch_12.pth", 
    #  "V2_e13":"exp1/train_1_v2_vgg_stage3/net_epoch_13.pth", 
    #  "V2_e14":"exp1/train_1_v2_vgg_stage3/net_epoch_14.pth", 
    #  "V2_e15":"exp1/train_1_v2_vgg_stage3/net_epoch_15.pth", 
    #  "V2_e16":"exp1/train_1_v2_vgg_stage3/net_epoch_16.pth", 
    #  "V2_e17":"exp1/train_1_v2_vgg_stage3/net_epoch_17.pth", 
    #  "V2_e18":"exp1/train_1_v2_vgg_stage3/net_epoch_18.pth", 
    #  "V2_e19":"exp1/train_1_v2_vgg_stage3/net_epoch_19.pth", 
    #  "V2_e20":"exp1/train_1_v2_vgg_stage3/net_epoch_20.pth", 
    #  "V2_e21":"exp1/train_1_v2_vgg_stage3/net_epoch_21.pth", 
    #  "V2_e22":"exp1/train_1_v2_vgg_stage3/net_epoch_22.pth", 
    #  "V2_e23":"exp1/train_1_v2_vgg_stage3/net_epoch_23.pth", 
    #  "V2_e24":"exp1/train_1_v2_vgg_stage3/net_epoch_24.pth", 
    #  "V2_e25":"exp1/train_1_v2_vgg_stage3/net_epoch_25.pth", 
    #  "V2_e26":"exp1/train_1_v2_vgg_stage3/net_epoch_26.pth",
    #  "V3_e9":"exp1/train_1_v3_vgg_stage3/net_epoch_9.pth", 
    #  "V3_e10":"exp1/train_1_v3_vgg_stage3/net_epoch_10.pth", 
    #  "V3_e11":"exp1/train_1_v3_vgg_stage3/net_epoch_11.pth", 
    #  "V3_e12":"exp1/train_1_v3_vgg_stage3/net_epoch_12.pth", 
    #  "V3_e13":"exp1/train_1_v3_vgg_stage3/net_epoch_13.pth", 
    #  "V3_e14":"exp1/train_1_v3_vgg_stage3/net_epoch_14.pth", 
    #  "V3_e15":"exp1/train_1_v3_vgg_stage3/net_epoch_15.pth", 
    #  "V3_e16":"exp1/train_1_v3_vgg_stage3/net_epoch_16.pth", 
    #  "V3_e17":"exp1/train_1_v3_vgg_stage3/net_epoch_17.pth", 
    #  "V3_e18":"exp1/train_1_v3_vgg_stage3/net_epoch_18.pth", 
    #  "V3_e19":"exp1/train_1_v3_vgg_stage3/net_epoch_19.pth", 
    #  "V3_e20":"exp1/train_1_v3_vgg_stage3/net_epoch_20.pth", 
    #  "V3_e21":"exp1/train_1_v3_vgg_stage3/net_epoch_21.pth", 
    #  "V3_e22":"exp1/train_1_v3_vgg_stage3/net_epoch_22.pth", 
    #  "V3_e23":"exp1/train_1_v3_vgg_stage3/net_epoch_23.pth", 
    #  "V3_e24":"exp1/train_1_v3_vgg_stage3/net_epoch_24.pth", 
    #  "V3_e25":"exp1/train_1_v3_vgg_stage3/net_epoch_25.pth",
    #  "V3_e26":"exp1/train_1_v3_vgg_stage3/net_epoch_26.pth", 
    #  "V3_e27":"exp1/train_1_v3_vgg_stage3/net_epoch_27.pth", 
    #  "V3_e28":"exp1/train_1_v3_vgg_stage3/net_epoch_28.pth", 
    #  "V3_e29":"exp1/train_1_v3_vgg_stage3/net_epoch_29.pth", 
    #  "V3_e30":"exp1/train_1_v3_vgg_stage3/net_epoch_30.pth",
    #  "V2V3_e1":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_1.pth", 
    #  "V2V3_e2":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_2.pth", 
    #  "V2V3_e3":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_3.pth", 
    #  "V2V3_e4":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_4.pth", 
    #  "V2V3_e5":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_5.pth", 
    #  "V2V3_e6":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_6.pth", 
    #  "V2V3_e7":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_7.pth", 
    #  "V2V3_e8":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_8.pth", 
    #  "V2V3_e9":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_9.pth", 
    #  "V2V3_e10":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_10.pth", 
    #  "V2V3_e11":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_11.pth", 
    #  "V2V3_e12":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_12.pth", 
    #  "V2V3_e13":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_13.pth", 
    #  "V2V3_e14":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_14.pth", 
    #  "V2V3_e15":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_15.pth", 
    #  "V2V3_e16":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_16.pth", 
    #  "V2V3_e17":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_17.pth", 
    #  "V2V3_e18":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_18.pth", 
    #  "V2V3_e19":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_19.pth", 
    #  "V2V3_e20":"exp1/train_1_v2+v3_vgg_stage3/net_epoch_20.pth", 

    #  "2_A":"train_2_HUGE_vgg-_stage3/net_epoch_5.pth", 
    #  "2_B":"train_2_HUGE_vgg-_stage3/net_epoch_10.pth", 
    #  "2_C":"train_2_HUGE_vgg-_stage3/net_epoch_15.pth", 
    #  "2_D":"train_2_HUGE_vgg-_stage3/net_epoch_20.pth", 

    #  "3_A":"train_3_HUGE_vgg-_stage3/net_epoch_5.pth", 
    #  "3_B":"train_3_HUGE_vgg-_stage3/net_epoch_10.pth", 
    #  "3_C":"train_3_HUGE_vgg-_stage3/net_epoch_15.pth", 
    #  "3_D":"train_3_HUGE_vgg-_stage3/net_epoch_20.pth", 
}

# Cuboid dimension in cm x,y,z
dimensions: {
    # "1_A" : [4.4,4.3,4.2], #1
    # "1_B" : [4.4,4.3,4.2], #1
    # "1_C" : [4.4,4.3,4.2], #1
    # "1_D" : [4.4,4.3,4.2], #1
    
    # "1_e1": [4.4,4.3,4.2], #1
    # "1_e2": [4.4,4.3,4.2], #1
    # "1_e3": [4.4,4.3,4.2], #1
    # "1_e4": [4.4,4.3,4.2], #1
    # "1_e5": [4.4,4.3,4.2], #1
    # "1_e6": [4.4,4.3,4.2], #1
    # "1_e7": [4.4,4.3,4.2], #1
    # "1_e8": [4.4,4.3,4.2], #1
    # "1_e9": [4.4,4.3,4.2], #1
    # "1_e10": [4.4,4.3,4.2], #1
    # "1_e11": [4.4,4.3,4.2], #1
    # "1_e12": [4.4,4.3,4.2], #1
    "1_e13": [4.4,4.3,4.2], #1
    "1_e14": [4.4,4.3,4.2], #1
    # "1_e15": [4.4,4.3,4.2], #1
    
    # "2_e1": [5.68,3.9,4.6], #2
    # "2_e2": [5.68,3.9,4.6], #2
    # "2_e3": [5.68,3.9,4.6], #2
    # "2_e4": [5.68,3.9,4.6], #2
    # "2_e5": [5.68,3.9,4.6], #2
    # "2_e6": [5.68,3.9,4.6], #2
    # "2_e7": [5.68,3.9,4.6], #2
    # "2_e8": [5.68,3.9,4.6], #2
    # "2_e9": [5.68,3.9,4.6], #2
    # "2_e10": [5.68,3.9,4.6], #2
    # "2_e11": [5.68,3.9,4.6], #2
    # "2_e12": [5.68,3.9,4.6], #2
    # "2_e13": [5.68,3.9,4.6], #2
    # "2_e14": [5.68,3.9,4.6], #2
    # "2_e15": [5.68,3.9,4.6], #2

    # "3_e1": [6.2,7,4.59],  #3
    # "3_e2": [6.2,7,4.59],  #3
    # "3_e3": [6.2,7,4.59],  #3
    # "3_e4": [6.2,7,4.59],  #3
    # "3_e5": [6.2,7,4.59],  #3
    # "3_e6": [6.2,7,4.59],  #3
    # "3_e7": [6.2,7,4.59],  #3
    # "3_e8": [6.2,7,4.59],  #3
    # "3_e9": [6.2,7,4.59],  #3
    # "3_e10": [6.2,7,4.59],  #3
    # "3_e11": [6.2,7,4.59],  #3
    # "3_e12": [6.2,7,4.59],  #3
    # "3_e13": [6.2,7,4.59],  #3
    # "3_e14": [6.2,7,4.59],  #3
    # "3_e15": [6.2,7,4.59],  #3
    # "2_A" : [5.68,3.9,4.6], #2
    # "2_B" : [3.9,5.68,4.6], #2
    # "2_C" : [5.68,3.9,4.6], #2
    # "2_D" : [3.9,5.68,4.6], #2

    # "V2_e1":[4.4,4.3,4.2], #1
    # "V2_e2":[4.4,4.3,4.2], #1
    # "V2_e3":[4.4,4.3,4.2], #1
    # "V2_e4":[4.4,4.3,4.2], #1
    # "V2_e5":[4.4,4.3,4.2], #1
    # "V2_e6":[4.4,4.3,4.2], #1
    # "V2_e7":[4.4,4.3,4.2], #1
    # "V2_e8":[4.4,4.3,4.2], #1
    # "V2_e9":[4.4,4.3,4.2], #1
    # "V2_e10":[4.4,4.3,4.2], #1
    # "V2_e11":[4.4,4.3,4.2], #1
    # "V2_e12":[4.4,4.3,4.2], #1
    # "V2_e13":[4.4,4.3,4.2], #1
    # "V2_e14":[4.4,4.3,4.2], #1
    # "V2_e15":[4.4,4.3,4.2], #1
    # "V2_e16":[4.4,4.3,4.2], #1
    # "V2_e17":[4.4,4.3,4.2], #1
    # "V2_e18":[4.4,4.3,4.2], #1
    # "V2_e19":[4.4,4.3,4.2], #1
    # "V2_e20":[4.4,4.3,4.2], #1
    # "V2_e21":[4.4,4.3,4.2], #1
    # "V2_e22":[4.4,4.3,4.2], #1
    # "V2_e23":[4.4,4.3,4.2], #1
    # "V2_e24":[4.4,4.3,4.2], #1
    # "V2_e25":[4.4,4.3,4.2], #1
    # "V2_e26":[4.4,4.3,4.2], #1
    
    # "V3_e1":[4.4,4.3,4.2], #1
    # "V3_e2":[4.4,4.3,4.2], #1
    # "V3_e3":[4.4,4.3,4.2], #1
    # "V3_e4":[4.4,4.3,4.2], #1
    # "V3_e5":[4.4,4.3,4.2], #1
    # "V3_e6":[4.4,4.3,4.2], #1
    # "V3_e7":[4.4,4.3,4.2], #1
    # "V3_e8":[4.4,4.3,4.2], #1
    # "V3_e9":[4.4,4.3,4.2], #1
    # "V3_e10":[4.4,4.3,4.2], #1
    # "V3_e11":[4.4,4.3,4.2], #1
    # "V3_e12":[4.4,4.3,4.2], #1
    # "V3_e13":[4.4,4.3,4.2], #1
    # "V3_e14":[4.4,4.3,4.2], #1
    # "V3_e15":[4.4,4.3,4.2], #1
    # "V3_e16":[4.4,4.3,4.2], #1
    # "V3_e17":[4.4,4.3,4.2], #1
    # "V3_e18":[4.4,4.3,4.2], #1
    # "V3_e19":[4.4,4.3,4.2], #1
    # "V3_e20":[4.4,4.3,4.2], #1
    # "V3_e21":[4.4,4.3,4.2], #1
    # "V3_e22":[4.4,4.3,4.2], #1
    # "V3_e23":[4.4,4.3,4.2], #1
    # "V3_e24":[4.4,4.3,4.2], #1
    # "V3_e25":[4.4,4.3,4.2], #1
    # "V3_e26":[4.4,4.3,4.2], #1
    # "V3_e27":[4.4,4.3,4.2], #1
    # "V3_e28":[4.4,4.3,4.2], #1
    # "V3_e29":[4.4,4.3,4.2], #1
    # "V3_e30":[4.4,4.3,4.2], #1
    
    # "V2V3_e1":[4.4,4.3,4.2], #1
    # "V2V3_e2":[4.4,4.3,4.2], #1
    # "V2V3_e3":[4.4,4.3,4.2], #1
    # "V2V3_e4":[4.4,4.3,4.2], #1
    # "V2V3_e5":[4.4,4.3,4.2], #1
    # "V2V3_e6":[4.4,4.3,4.2], #1
    # "V2V3_e7":[4.4,4.3,4.2], #1
    # "V2V3_e8":[4.4,4.3,4.2], #1
    # "V2V3_e9":[4.4,4.3,4.2], #1
    # "V2V3_e10":[4.4,4.3,4.2], #1
    # "V2V3_e11":[4.4,4.3,4.2], #1
    # "V2V3_e12":[4.4,4.3,4.2], #1
    # "V2V3_e13":[4.4,4.3,4.2], #1
    # "V2V3_e14":[4.4,4.3,4.2], #1
    # "V2V3_e15":[4.4,4.3,4.2], #1

    # "3_A" : [6.2,7,4.59],  #3
    # "3_B" : [6.2,7,4.59],  #3
    # "3_C" : [6.2,7,4.59],  #3
    # "3_D" : [6.2,7,4.59],  #3

}

draw_colors: {
    # "1_A" : [13, 255, 128],  # green
    # "1_B" : [255, 255, 255],  # while
    # "1_C" : [0, 104, 255],  # blue
    # "1_D" : [217,12, 232],  # magenta

    # "1_e1":[13, 255, 128],
    # "1_e2":[255, 255, 255],
    # "1_e3":[0, 104, 255],
    # "1_e4":[217,12, 232],  #
    # "1_e5":[13, 255, 128],
    # "1_e6":[255, 255, 255],
    # "1_e7":[0, 104, 255],
    # "1_e8":[217,12, 232],  #
    # "1_e9":[13, 255, 128],
    # "1_e10":[255, 255, 255],
    # "1_e11":[0, 104, 255],
    # "1_e12":[217,12, 232],  #
    "1_e13":[255, 255, 255],
    "1_e14":[0, 104, 255],
    # "1_e15":[217,12, 232],  #

    # "2_e1":[13, 255, 128],
    # "2_e2":[255, 255, 255],
    # "2_e3":[0, 104, 255],
    # "2_e4":[217,12, 232],  #
    # "2_e5":[13, 255, 128],
    # "2_e6":[255, 255, 255],
    # "2_e7":[0, 104, 255],
    # "2_e8":[217,12, 232],  #
    # "2_e9":[13, 255, 128],
    # "2_e10":[255, 255, 255],
    # "2_e11":[0, 104, 255],
    # "2_e12":[217,12, 232],  #
    # "2_e13":[255, 255, 255],
    # "2_e14":[0, 104, 255],
    # "2_e15":[217,12, 232],  #

    # "3_e1":[13, 255, 128],
    # "3_e2":[255, 255, 255],
    # "3_e3":[0, 104, 255],
    # "3_e4":[217,12, 232],  #
    # "3_e5":[13, 255, 128],
    # "3_e6":[255, 255, 255],
    # "3_e7":[0, 104, 255],
    # "3_e8":[217,12, 232],  #
    # "3_e9":[13, 255, 128],
    # "3_e10":[255, 255, 255],
    # "3_e11":[0, 104, 255],
    # "3_e12":[217,12, 232],  #
    # "3_e13":[255, 255, 255],
    # "3_e14":[0, 104, 255],
    # "3_e15":[217,12, 232],  #

    # "V2_e1":[13, 255, 128],
    # "V2_e2":[255, 255, 255],
    # "V2_e3":[0, 104, 255],
    # "V2_e4":[217,12, 232],  #
    # "V2_e5":[13, 255, 128],
    # "V2_e6":[255, 255, 255],
    # "V2_e7":[0, 104, 255],
    # "V2_e8":[217,12, 232],  #
    # "V2_e9":[13, 255, 128],
    # "V2_e10":[13, 255, 128],
    # "V2_e11":[255, 255, 255],
    # "V2_e12":[0, 104, 255],
    # "V2_e13":[217,12, 232],  #
    # "V2_e14":[13, 255, 128],
    # "V2_e15":[255, 255, 255],
    # "V2_e16":[255, 255, 255],
    # "V2_e17":[0, 104, 255],
    # "V2_e18":[217,12, 232],  #
    # "V2_e19":[13, 255, 128],
    # "V2_e20":[255, 255, 255],
    # "V2_e21":[255, 255, 255],
    # "V2_e22":[0, 104, 255],
    # "V2_e23":[217,12, 232],  #
    # "V2_e24":[13, 255, 128],
    # "V2_e25":[255, 255, 255],
    # "V2_e26":[255, 255, 255],

    # "V3_e1":[0, 104, 255],
    # "V3_e2":[217,12, 232],  #
    # "V3_e3":[13, 255, 128],
    # "V3_e4":[13, 255, 128],
    # "V3_e5":[255, 255, 255],
    # "V3_e6":[0, 104, 255],
    # "V3_e7":[217,12, 232],  #
    # "V3_e8":[13, 255, 128],
    # "V3_e9":[255, 255, 255],
    # "V3_e10":[0, 104, 255],
    # "V3_e11":[217,12, 232],  #
    # "V3_e12":[13, 255, 128],
    # "V3_e13":[13, 255, 128],
    # "V3_e14":[255, 255, 255],
    # "V3_e15":[255, 255, 255],
    # "V3_e16":[217,12, 232],  #
    # "V3_e17":[13, 255, 128],
    # "V3_e18":[13, 255, 128],
    # "V3_e19":[255, 255, 255],
    # "V3_e20":[0, 104, 255],
    # "V3_e21":[217,12, 232],  #
    # "V3_e22":[13, 255, 128],
    # "V3_e23":[13, 255, 128],
    # "V3_e24":[255, 255, 255],
    # "V3_e25":[255, 255, 255],
    # "V3_e26":[217,12, 232],  #
    # "V3_e27":[13, 255, 128],
    # "V3_e28":[13, 255, 128],
    # "V3_e29":[255, 255, 255],
    # "V3_e30":[0, 104, 255],
    # "V2V3_e1":[217,12, 232],  #
    # "V2V3_e2":[13, 255, 128],
    # "V2V3_e3":[255, 255, 255],
    # "V2V3_e4":[0, 104, 255],
    # "V2V3_e5":[217,12, 232],  #
    # "V2V3_e6":[217,12, 232],  #
    # "V2V3_e7":[13, 255, 128],
    # "V2V3_e8":[255, 255, 255],
    # "V2V3_e9":[0, 104, 255],
    # "V2V3_e10":[217,12, 232],  #
    # "V2V3_e11":[217,12, 232],  #
    # "V2V3_e12":[13, 255, 128],
    # "V2V3_e13":[255, 255, 255],
    # "V2V3_e14":[0, 104, 255],
    # "V2V3_e15":[217,12, 232],  #
    
    # "2_A" : [13, 255, 128],  # green
    # "2_B" : [255, 255, 255],  # while
    # "2_C" : [0, 104, 255],  # blue
    # "2_D" : [217,12, 232],  # magenta

    # "3_A" : [13, 255, 128],  # green
    # "3_B" : [255, 255, 255],  # while
    # "3_C" : [0, 104, 255],  # blue
    # "3_D" : [217,12, 232],  # magenta
}

# Camera intrinsics (Logitech C920)
camera_settings: {
    "name": "Viewpoint",
    "width": 512,
    "height": 512,
    "fx": 256,
    "fy": 256,
    "cx": 256,
    "cy": 256
}

# Config params for DOPE
thresh_angle: 0.5
thresh_map: 0.01
sigma: 3
thresh_points: 0.1
