topic_camera: "/dope/webcam_rgb_raw"
topic_publishing: "dope"
frame_id: "/dope"

# Comment any of these lines to prevent detection / pose estimation of that object
weights: {
    "1_A":"train_1_HUGE_vgg-_stage3/net_epoch_5.pth", 
    "1_B":"train_1_HUGE_vgg-_stage3/net_epoch_52.pth", 
    "2_A":"train_2_HUGE_vgg-_stage3_2+/net_epoch_5.pth", 
    "2_B":"train_2_HUGE_vgg-_stage3_2+/net_epoch_31.pth", 
    "3_A":"train_3_HUGE_vgg-_stage3/net_epoch_5.pth", 
    "3_B":"train_3_HUGE_vgg-_stage3/net_epoch_16.pth",
}

# Cuboid dimension in cm x,y,z
dimensions: {
    "1_A" : [4.4,4.3,4.2], #1
    "1_B" : [4.4,4.3,4.2], #1
    "2_A" : [5.68,3.9,4.6], #2
    "2_B" : [5.68,3.9,4.6], #2
    "3_A" : [6.2,7,4.59], #3
    "3_B" : [6.2,7,4.59], #3
}

draw_colors: {
    "1_A" : [13, 255, 128],  # green
    "1_B" : [255, 255, 255],  # while
    "2_A" : [0, 104, 255],  # blue
    "2_B" : [217,12, 232],  # magenta
    "3_A" : [255, 101, 0],  # orange
    "3_B" : [232, 222, 12],  # yellow
}

# Camera intrinsics (Logitech C920)
camera_settings: {
    "name": "logitech_c920",
    "width": 640,
    "height": 480,
    "fx": 641.5,
    "fy": 641.5,
    "cx": 320.0,
    "cy": 240.0
}

# Config params for DOPE
thresh_angle: 0.5
thresh_map: 0.01
sigma: 3
thresh_points: 0.1
