topic_camera: "/dope/webcam_rgb_raw"
topic_publishing: "dope"
frame_id: "/dope"

# Comment any of these lines to prevent detection / pose estimation of that object
weights: {
     "V3_e15":"exp1/train_1_v3_vgg_stage3/net_epoch_15.pth", 
     "V3_e16":"exp1/train_1_v3_vgg_stage3/net_epoch_16.pth", 
     "V3_e17":"exp1/train_1_v3_vgg_stage3/net_epoch_17.pth", 
     "V3_e18":"exp1/train_1_v3_vgg_stage3/net_epoch_18.pth", 
     "V3_e19":"exp1/train_1_v3_vgg_stage3/net_epoch_19.pth", 
     "V3_e20":"exp1/train_1_v3_vgg_stage3/net_epoch_20.pth", 
     "V3_e21":"exp1/train_1_v3_vgg_stage3/net_epoch_21.pth", 
     "V3_e22":"exp1/train_1_v3_vgg_stage3/net_epoch_22.pth", 
     "V3_e23":"exp1/train_1_v3_vgg_stage3/net_epoch_23.pth", 
     "V3_e24":"exp1/train_1_v3_vgg_stage3/net_epoch_24.pth", 
     "V3_e25":"exp1/train_1_v3_vgg_stage3/net_epoch_25.pth",
     "V3_e26":"exp1/train_1_v3_vgg_stage3/net_epoch_26.pth", 
     "V3_e27":"exp1/train_1_v3_vgg_stage3/net_epoch_27.pth", 
     "V3_e28":"exp1/train_1_v3_vgg_stage3/net_epoch_28.pth", 
     "V3_e29":"exp1/train_1_v3_vgg_stage3/net_epoch_29.pth", 
     "V3_e30":"exp1/train_1_v3_vgg_stage3/net_epoch_30.pth"
}

# Cuboid dimension in cm x,y,z
dimensions: {
    "V3_e15":[4.4,4.3,4.2], #1
    "V3_e16":[4.4,4.3,4.2], #1
    "V3_e17":[4.4,4.3,4.2], #1
    "V3_e18":[4.4,4.3,4.2], #1
    "V3_e19":[4.4,4.3,4.2], #1
    "V3_e20":[4.4,4.3,4.2], #1
    "V3_e21":[4.4,4.3,4.2], #1
    "V3_e22":[4.4,4.3,4.2], #1
    "V3_e23":[4.4,4.3,4.2], #1
    "V3_e24":[4.4,4.3,4.2], #1
    "V3_e25":[4.4,4.3,4.2], #1
    "V3_e26":[4.4,4.3,4.2], #1
    "V3_e27":[4.4,4.3,4.2], #1
    "V3_e28":[4.4,4.3,4.2], #1
    "V3_e29":[4.4,4.3,4.2], #1
    "V3_e30":[4.4,4.3,4.2]
}

draw_colors: {
    "V3_e15":[0,0,1],
    "V3_e16":[0,0,2],
    "V3_e17":[0,0,3],
    "V3_e18":[0,0,4],
    "V3_e19":[0,0,5],
    "V3_e20":[0,0,6],
    "V3_e21":[0,0,7],
    "V3_e22":[0,0,8],
    "V3_e23":[0,0,9],
    "V3_e24":[0,0,10],
    "V3_e25":[0,0,11],
    "V3_e26":[0,0,12], 
    "V3_e27":[0,0,13],
    "V3_e28":[0,0,14],
    "V3_e29":[0,0,15],
    "V3_e30":[0,0,16]
}

# Camera intrinsics (Logitech C920)
camera_settings: {
    "name": "logitech_c920",
    "width": 512,
    "height": 512,
    "fx": 256,
    "fy": 256,
    "cx": 256,
    "cy": 256
}

# Config params for DOPE
thresh_angle: 0.5
thresh_map: 0.01
sigma: 3
thresh_points: 0.1
